=== LotKorn/Dino2015XML/dinoschema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
				<xs:element name="dinosaurawrier">
								<xs:complexType>
												<xs:sequence>
																<xs:element name="dinosaurier">
																				<xs:complexType>
																								<xs:sequence>
																												<xs:element maxOccurs="unbounded" name="dino" nillable="false" type="dinoTyp"/>
																								</xs:sequence>
																				</xs:complexType>
																</xs:element>
																<xs:element name="klassen">
																				<xs:complexType>
																								<xs:sequence>
																												<xs:element maxOccurs="unbounded" name="klassenBeschreibung" type="klasseTyp"/>
																								</xs:sequence>
																				</xs:complexType>
																</xs:element>
																<xs:element name="merkmale">
																				<xs:complexType>
																								<xs:sequence>
																												<xs:element maxOccurs="unbounded" name="nahrung" type="nahrungTyp"/>
																												<xs:element maxOccurs="unbounded" name="fortbewegung" type="fortbewegungsTyp"/>
																												<xs:element maxOccurs="unbounded" name="periode" type="periodeTyp"/>
																								</xs:sequence>
																				</xs:complexType>
																</xs:element>
												</xs:sequence>
								</xs:complexType>
				</xs:element>
				<xs:complexType name="dinoTyp">
								<xs:sequence>
												<xs:element maxOccurs="1" minOccurs="1" name="nameDe" nillable="false" type="xs:string"/>
												<xs:element maxOccurs="1" minOccurs="1" name="nameLat" nillable="false" type="xs:string"/>
												<xs:element maxOccurs="1" name="größe" type="größeTyp"/>
												<xs:element name="gewicht" type="gewichtTyp"/>
												<xs:element maxOccurs="1" name="periode" type="periodeTyp"/>
												<xs:element maxOccurs="1" name="klasse" type="klasseSuperTyp"/>
												<xs:element maxOccurs="unbounded" minOccurs="0" name="merkmal" type="xs:string"/>
												<xs:element maxOccurs="unbounded" minOccurs="0" name="bild" type="bildTyp"/>
												<xs:element maxOccurs="1" name="beschreibung" type="beschreibungTyp"/>
												<xs:element maxOccurs="unbounded" name="verbreitung" type="xs:string"/>
												<xs:element maxOccurs="unbounded" minOccurs="0" name="link" type="xs:string"/>
								</xs:sequence>
				</xs:complexType>
				<xs:complexType name="größeTyp">
								<xs:all>
												<xs:element default="0" maxOccurs="1" minOccurs="0" name="höhe" type="xs:float"/>
												<xs:element default="0" maxOccurs="1" minOccurs="0" name="breite" type="xs:float"/>
												<xs:element default="0" maxOccurs="1" minOccurs="0" name="länge" type="xs:float"/>
								</xs:all>
				</xs:complexType>
				<xs:complexType name="periodeTyp">
								<xs:sequence>
												<xs:element maxOccurs="unbounded" minOccurs="0" name="periodeName" type="periodeName"/>
												<xs:element maxOccurs="1" minOccurs="0" name="periodeVon" type="periodeZeit"/>
												<xs:element maxOccurs="1" minOccurs="0" name="periodeBis" type="periodeZeit"/>
								</xs:sequence>
				</xs:complexType>
				<xs:simpleType name="periodeName">
								<xs:restriction base="xs:string">
												<xs:enumeration value="Kambrium"/>
												<xs:enumeration value="Ordovizium"/>
												<xs:enumeration value="Silur"/>
												<xs:enumeration value="Devon"/>
												<xs:enumeration value="Karbon"/>
												<xs:enumeration value="Perm"/>
												<xs:enumeration value="Trias"/>
												<xs:enumeration value="Jura"/>
												<xs:enumeration value="Kreide"/>
								</xs:restriction>
				</xs:simpleType>
				<xs:simpleType name="periodeZeit">
								<xs:restriction base="xs:integer">
												<xs:maxInclusive value="541"/>
												<xs:minInclusive value="66"/>
								</xs:restriction>
				</xs:simpleType>
				<xs:complexType name="gewichtTyp">
								<xs:all>
												<xs:element maxOccurs="1" minOccurs="0" name="min" type="gewichtBasisTyp"/>
												<xs:element maxOccurs="1" minOccurs="0" name="max" type="gewichtBasisTyp"/>
								</xs:all>
				</xs:complexType>
				<xs:simpleType name="gewichtBasisTyp">
								<xs:restriction base="xs:float">
												<xs:minExclusive value="0"/>
								</xs:restriction>
				</xs:simpleType>
				<xs:simpleType name="klasseBasisTyp">
								<xs:restriction base="xs:string">
												<xs:enumeration value="Ornithischia"/>
												<xs:enumeration value="Heterodontosauridae"/>
												<xs:enumeration value="Stegosauria"/>
												<xs:enumeration value="Ankylosauria"/>
												<xs:enumeration value="Pachycephalosauria"/>
												<xs:enumeration value="Ceratopsia"/>
												<xs:enumeration value="Ornithopoda"/>
												<xs:enumeration value="Saurischia"/>
												<xs:enumeration value="Prosauropoda"/>
												<xs:enumeration value="Sauropoda"/>
												<xs:enumeration value="Theropoda"/>
												<xs:enumeration value="Coelophysoidea"/>
												<xs:enumeration value="Ceratosauria"/>
												<xs:enumeration value="Spinosauroidea"/>
												<xs:enumeration value="Carnosauria"/>
												<xs:enumeration value="Tyrannosauroidea"/>
												<xs:enumeration value="Ornithomimosauria"/>
												<xs:enumeration value="Therizinosauroidea"/>
												<xs:enumeration value="Alvarezsauroidea"/>
												<xs:enumeration value="Oviraptorosauria"/>
												<xs:enumeration value="Troodontidae"/>
												<xs:enumeration value="Dromaeosauridae"/>
												<xs:enumeration value="Avialae"/>
								</xs:restriction>
				</xs:simpleType>
				<xs:complexType name="klasseSuperTyp">
								<xs:sequence>
												<xs:element name="name" type="klasseBasisTyp" maxOccurs="1" minOccurs="1"/>
												<xs:element name="fortbewegung" type="fortbewegungsTyp" maxOccurs="1" minOccurs="1"/>
												<xs:element name="nahrung" type="nahrungTyp" maxOccurs="1" minOccurs="1"/>
								</xs:sequence>
				</xs:complexType>
				<xs:complexType name="klasseTyp">
								<xs:sequence>
												<xs:element name="klasse" type="klasseBasisTyp"/>
												<xs:element name="beschreibung" type="xs:string"/>
								</xs:sequence>
				</xs:complexType>
				<xs:simpleType name="nahrungTyp">
								<xs:restriction base="xs:string">
												<xs:enumeration value="Pflanzenfresser"/>
												<xs:enumeration value="Fleischfresser"/>
												<xs:enumeration value="Allesfresser"/>
								</xs:restriction>
				</xs:simpleType>
				<xs:simpleType name="fortbewegungsTyp">
								<xs:restriction base="xs:string">
												<xs:enumeration value="Zweibeinig"/>
												<xs:enumeration value="Vierbeinig"/>
												<xs:enumeration value="Flügel"/>
												<xs:enumeration value="Sonstiges"/>
								</xs:restriction>
				</xs:simpleType>
				<xs:complexType name="bildTyp">
								<xs:all>
												<xs:element name="url" type="xs:string"/>
												<xs:element name="copyright" type="xs:string"/>
												<xs:element minOccurs="1" name="typ" type="bildArt"/>
												<xs:element name="titel" type="xs:string"/>
												<xs:element name="beschreibung" type="xs:string"/>
								</xs:all>
				</xs:complexType>
				<xs:complexType name="beschreibungTyp">
								<xs:sequence>
												<xs:element name="kurzbeschreibung" type="xs:string"/>
												<xs:element name="texte" type="beschreibungBasisTyp" maxOccurs="unbounded"/>
								</xs:sequence>
				</xs:complexType>
				<xs:complexType name="beschreibungBasisTyp">
								<xs:all>
												<xs:element name="titel" type="xs:string"/>
												<xs:element name="text" type="xs:string"/>
								</xs:all>
				</xs:complexType>
				<xs:simpleType name="bildArt">
								<xs:restriction base="xs:string">
												<xs:enumeration value="größe"/>
												<xs:enumeration value="zeichnung"/>
												<xs:enumeration value="profil"/>
												<xs:enumeration value="fußabdruck"/>
												<xs:enumeration value="skelett"/>
								</xs:restriction>
				</xs:simpleType>
</xs:schema>

=== LotKorn/Dino2015XML/dinoxml.xml
<?xml version="1.0" encoding="UTF-8"?>

<dinosaurawrier xsi:noNamespaceSchemaLocation="dinoschema.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
				<dinosaurier>
								<dino>
												<nameDe>Tyrannosaurus</nameDe>
												<nameLat>Tyrannosaurus rex</nameLat>
												<größe>
																<höhe>4</höhe>
																<breite/>
																<länge>12.4</länge>
												</größe>
												<gewicht>
																<min>3000</min>
																<max>6800</max>
												</gewicht>
												<periode>
																<periodeName>Kreide</periodeName>
																<periodeVon>66</periodeVon>
																<periodeBis>68</periodeBis>
												</periode>
												<klasse>
																<name>Tyrannosauroidea</name>
																<fortbewegung>Zweibeinig</fortbewegung>
																<nahrung>Fleischfresser</nahrung>
												</klasse>
												<merkmal>Kleine Gliedmaßen</merkmal>
												<merkmal>Gigantischer Schädel</merkmal>
												<bild>
																<url>http://upload.wikimedia.org/wikipedia/commons/3/33/Senckenberganlage_%28DerHexer%29_2012-05-11_04.jpg</url>
																<copyright>Wikipedia Commons</copyright>
																<typ>profil</typ>
																<titel>Modell vom Tyrannosaurus</titel>
																<beschreibung>Modell am Naturmuseum Senckenberg; die Haltung entspricht den aktuellen Erkenntnissen</beschreibung>
												</bild>
												<bild>
																<url>http://upload.wikimedia.org/wikipedia/commons/a/a3/Tyrannosaurusscale.png</url>
																<copyright>Wikipedia Commons</copyright>
																<typ>größe</typ>
																<titel>Größenvergleich</titel>
																<beschreibung>Beinahe 13 Meter lang und 4 Meter Schulterhöhe</beschreibung>
												</bild>
												<bild>
																<url>http://bunteerde.planeterde.de/Members/lutz/tiere-und-natur/t-rex-knochen-mit-geschichte/Fussabdruck_T-Rex.jpg/image</url>
																<copyright>Bunte Erde</copyright>
																<typ>fußabdruck</typ>
																<titel>Fußabdruck</titel>
																<beschreibung>Fußabdruck vom "T-Rex"</beschreibung>
												</bild>
												<bild>
																<url>http://upload.wikimedia.org/wikipedia/commons/3/33/Stan_the_Trex_at_Manchester_Museum.jpg</url>
																<copyright>Wikipedia Commons</copyright>
																<typ>skelett</typ>
																<titel>Skelettrekonstruktion</titel>
																<beschreibung>Das Tyrannosaurus-Exemplar „Stan“ im Manchester Museum</beschreibung>
												</bild>
												<beschreibung>
																<kurzbeschreibung>Der größte und bekannteste "Tyrann" der Urzeit</kurzbeschreibung>
																<texte>
																				<titel>Großer Kopf mit kräftiger Halsmuskulatur</titel>
																				<text>Sein Kopf erreichte eine Länge von 1,25 Metern und besaß Ansatzflächen für eine kräftige Beißmuskulatur. Die Knochen des Schädels waren überwiegend lose miteinander verbunden, so dass die Wucht, mit der er seine Zähne in seine Beute schlug, abgefedert wurde. Die Knochen im Oberteil des Schädels waren hingegen verstärkt und unterstützten die Beißkraft (vgl. Nachricht vom Juni 2004).

Die Beißkraft eines erwachsenen Tyrannosaurus lag schätzungsweise bei 35.000 bis 52.000 Newton, was ihn zum kräftigsten Beißer im gesamten Tierreicht macht  und seinen Ruf als "fürchterlichsten Räuber aller Zeiten" bestätigte. (Lediglich das Urzeitkrokodil Deinosuchus riograndensis konnte wahrscheinlich noch kräftiger zubeißen als Tyrannosaurus rex.)
		

Der Schädel des Tyrannosaurus rex wurde 1,25 Meter und seine Zaähne bis zu 23 Zentimeter lang.

Im Maul des Tyrannosaurus rex saßen bis zu 23 Zentimeter lange, sägeblattartige Zähne.

Sein Hals war kurz und muskulös. Die Halsmuskeln erlaubten es ihm, seinen Kopf mit viel Kraft hin und her zu bewegen oder schnell nach hinten zu ziehen, und so seine Beute mit kräftigen Kopfbewegungen zu zerreißen</text>
																</texte>
												</beschreibung>
												<verbreitung>Nordamerika</verbreitung>
												<link>http://de.wikipedia.org/wiki/Tyrannosaurus</link>
												<link>http://www.dinosaurier-interesse.de/web/Saurierarten/Tyrannosaurus.html</link>
								</dino>
								<dino>
												<nameDe>Stegosaurus</nameDe>
												<nameLat>Stegosaurus armatus</nameLat>
												<größe>
																<höhe>4</höhe>
																<länge>9</länge>
												</größe>
												<gewicht>
																<min>2300</min>
																<max>4500</max>
												</gewicht>
												<periode>
																<periodeName>Jura</periodeName>
																<periodeVon>147</periodeVon>
																<periodeBis>157</periodeBis>
												</periode>
												<klasse>
																<name>Stegosauria</name>
																<fortbewegung>Vierbeinig</fortbewegung>
																<nahrung>Pflanzenfresser</nahrung>
												</klasse>
												<merkmal>Rückenplatten</merkmal>
												<merkmal>Schwanzstacheln</merkmal>
												<bild>
																<url>http://upload.wikimedia.org/wikipedia/commons/8/8b/Ba%C5%82t%C3%B3w_Park_Jurajski_001.jpg</url>
																<copyright>Wikipedia Commons</copyright>
																<typ>profil</typ>
																<titel>Modell von Stegosaurus</titel>
																<beschreibung>Modell von Stegosaurus im Bałtów Jurassic Park, Bałtów, Polen</beschreibung>
												</bild>
												<bild>
																<url>http://upload.wikimedia.org/wikipedia/commons/7/73/Stegosaurus_size.png</url>
																<copyright>Wikipedia Commons</copyright>
																<typ>größe</typ>
																<titel>Größenvergleich</titel>
																<beschreibung>9 Meter Lang, 4 Meter Hoch, möglicherweise bis zu 8 Meter aufrecht Stehend</beschreibung>
												</bild>
												<bild>
																<url>http://palaeo.gly.bris.ac.uk/palaeofiles/fossilgroups/stegosauria/Images/susamnh.JPG</url>
																<copyright>University of Bristol</copyright>
																<typ>fußabdruck</typ>
																<titel>Fußabdruck</titel>
																<beschreibung>Fossile Fußspuren von Stegosauriden sind extrem selten, vor 1996 war keine einzige bekannt. Einige Forscher vermuten, dass Stegosaurier eher trockene Gebiete besiedelten, und dass deswegen so wenig Spurenfunde aufgetaucht sind.</beschreibung>
												</bild>
												<bild>
																<url>http://upload.wikimedia.org/wikipedia/commons/7/70/Stegosaurus_BW.jpg</url>
																<copyright>Wikipedia Commons</copyright>
																<typ>zeichnung</typ>
																<titel>Künstlerische Darstellung</titel>
																<beschreibung>Mögliches Aussehen eines Stegosauriers</beschreibung>
												</bild>
												<bild>
																<url>http://upload.wikimedia.org/wikipedia/commons/9/99/Paleontology_Exhibit%2C_Stegosaurus-_Armored_Dinosaur.jpg</url>
																<copyright>Wikipedia Commons</copyright>
																<typ>skelett</typ>
																<titel>Skelettrekonstruktion</titel>
																<beschreibung>Skelettrekonstruktion von Stegosaurus, vermutlich aufgenommen in den 1930er Jahren, mit alternierend angeordneten, stehenden Rückenplatten im National Museum of Natural History in Washington, D. C.</beschreibung>
												</bild>
												<beschreibung>
																<kurzbeschreibung>Ein mittelgroßer, vierbeiniger Pflanzenfresser. Besonders bekannt durch seine Rückenplatten.</kurzbeschreibung>
																<texte>
																				<titel>Allgemeine Informationen</titel>
																				<text>Dieser bis 9 Meter lange Dinosaurier ist wohl der bekannteste unter den Stegosauriern. 1877 veröffentlichte Othniel Charles Marsh (amerikanischer Paläontologe) zum ersten Mal die Beschreibung der Überreste, die in den Steinbrüchen von Colorado und Wyoming gefunden wurden. Die Beschreibung eines vollständigen Skeletts gelang ihm aber erst 1891.

Der Stegosaurus besaß breite Rückenplatten, von denen die größte bis über 60 cm hoch werden konnte. Da sein Skelett an den Wirbeln der Beckengegend und der Schwanzbasis lange, nach oben gerichtete Fortsätze aufweist, die wahrscheinlich als Ansatzstelle für starke Rückenmuskeln dienten, vermuten einige Wissenschaftler, dass dieser Stegosaurus in der Lage war, sich am Baum abgestützt auf die Hinterbeine zu erheben, um weiter höher hängende Blätter abzuweiden.

Der Kopf des Stegosaurus war etwa 40 cm lang und beherbergte das Gehirn von der Größe einer Wallnuss.</text>
																</texte>
												</beschreibung>
												<verbreitung>Nordamerika</verbreitung>
												<verbreitung>Europa</verbreitung>
												<link>http://www.dinosaurier-interesse.de/web/Saurierarten/Stegosaurus.html</link>
												<link>http://de.wikipedia.org/wiki/Stegosauria</link>
								</dino>
								<dino>
												<nameDe>Triceratops</nameDe>
												<nameLat>Triceratops</nameLat>
												<größe>
																<höhe>3</höhe>
																<länge>9</länge>
												</größe>
												<gewicht>
																<min>6000</min>
																<max>12000</max>
												</gewicht>
												<periode>
																<periodeName>Kreide</periodeName>
																<periodeVon>66</periodeVon>
																<periodeBis>68</periodeBis>
												</periode>
												<klasse>
																<name>Ceratopsia</name>
																<fortbewegung>Vierbeinig</fortbewegung>
																<nahrung>Pflanzenfresser</nahrung>
												</klasse>
												<merkmal>Dreihorn-Schädel</merkmal>
												<bild>
																<url>http://upload.wikimedia.org/wikipedia/commons/c/c7/Triceratops_-_JuraPark_Baltow.JPG</url>
																<copyright>Wikipedia Commons</copyright>
																<typ>profil</typ>
																<titel>Modell von Stegosaurus</titel>
